---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: raven-os
# description will be included in the image's metadata
description: Based on Wayblue niri-nvidia-open image, added nix, quickshell.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/niri-nvidia-open
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # nix package manager
  - type: script
    snippets:
    - "dnf5 install -y nix"
    - "mkdir -p /nix /var/nix"
    - "dnf5 clean all"

  # - type: files
  #   files:
  #     - source: systemd/nix.mount
  #       destination: /etc/systemd/system/nix.mount

  - type: systemd
    system:
      enabled:
        - nix.mount
        - nix-daemon.service

  # custom packages
  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - lihaohong/yazi
          - avengemedia/dms
      # Error: Enabling rpmfusion repos
      #        Enabling 'fedora-cisco-openh264' repo for RPMFusion compatibility
      #        No matching repository to modify: fedora-cisco-openh264
      # nonfree: rpmfusion

    install:
      skip-unavailable: true
      packages:
        - dms
        - kitty
        - fastfetch
        - yazi
        - btop
        - htop
        # - steam # needs rpmfusion
    remove:
      packages:
        - alacritty
        - rofi-wayland
        - wofi

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
